fix precommit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,9 +3,9 @@
 
  npx prettier --write . "tests/data/*.json"  
 
- if [ $? -ne 0 ]; then
-  echo "Linting or formatting errors found. Please fix them before committing."
-  exit 1
+ if ! npx prettier --check . "tests/data/*.json"; then
+   echo "Formatting errors found. Please fix them before committing."
+   exit 1
  fi
 
   npm run lint
